### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/maket-2#10]
Проверь еще раз имена классов на соответствие БЭМ `event__post__content__date`

**Comment by mrNemoZero** [comment]
Да в меня Сатана вселился и я начал что то чудить:))

**Comment by mrNemoZero** [comment]
Вот index.pug структуру можно так делать. ?

**Comment by Burize** [comment]
А что не так со структурой? Если ты про то, что не верстка не разбита на отдельные блоки для групп элементов (кнопок, PieChart, форм и тд), а все идет сплошным потоком в .index.pug, то это нормально для этого задания.

**Comment by Burize** [comment]
`Более к БЭМ пееделал, вроде получше но все ранво не очень:/` - ну сейчас по крайней мере соответствует правилам БЭМ.

**Comment by Burize** [comment]
Добавь keyword в head у index и закрывай issue.

**Comment by mrNemoZero** [comment]
да я больше про длинные имена, но хотя сразу понятно, что это за блок, я за это переживал)

**Comment by mrNemoZero** [comment]
оЙ, эот у первого макета изменил, ща у вторго добавлю
