### ISSUE TITLE
index.styl

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-2#12]
Сейчас харкодится контейнер для каждого блока. Попытайся реализовать более универсальное решение (считай - универсальные контейнеры). Если не получится, то вынеси в миксин создание контейнера

**Comment by mrNemoZero** [comment]
т.е. создать так сказать несколько классов для всех так? Я думал об этом, но отступы между блоками разные, по крайней мере везде марждин топ разный. Или  я че то не правильно понял?

**Comment by Zarwlar** [comment]
Как вариант можно сделать универсальные блоки, а выравнивать их через селектор ".container .block". Возможно через ".container > .block"

**Comment by mrNemoZero** [comment]
Вот  втаком виде начал делать пойдет? родительскй блок это контйнер для всех
            & > .button
                margin-bottom 1.2rem
                &:nth-child(4n+1)
                    margin-left 4.7rem
                &:nth-child(4n+4)
                    margin-right 3.8rem
            & > .arrow
                &:first-child
                    margin-left 1.2rem
                &:last-child
                    margin-right 1.2rem_

**Comment by mrNemoZero** [comment]
Вот примерно так будет норм? я пока вертикально не спозиционировал. Пока не знаю как это лучше сделать. Хидэра хардкодятся пока

**Comment by mrNemoZero** [comment]
Вот првда хидер не очень не знаю как сделть( Хотел через attr() в css, но походу это не работает. Js  подключать не хочу. Или эти все классы в миксин вывести в хидере? Может я че то упускаю)
