### ISSUE TITLE
Общий ишус, включающий ишусы из первого макета

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-2#13]
1) Перейти от px к em
2) Pieces
3) Способ передачи аргументов в миксин (функцию)

**Comment by mrNemoZero** [comment]
Ну вот передача наример типа кнопки не объектом же передавать, или все аргументы в миксин должны передаваься в виде одного объекта, а в миксине уже думать что делать с этими данными?)
Ну вот стрелочные нопки у меня на вход педеается left, right... Их тоже хранит в файле одном и оттудасчитвать в объект?
