### ISSUE TITLE
JS Файлы

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-2#14]
Каждый блок должен быть оформлен в each.

**Comment by mrNemoZero** [comment]
Не совсем понял((  это как?)

**Comment by Zarwlar** [comment]
Каждый БЭМ объект на странице может быть переиспользован n-ое количество раз. Если не инстанцировать в JS-е эти блоки, то есть не предоставлять каждому блоку собственный this, то как минимум, это будет грозить некорректной работой скрипта блока

**Comment by mrNemoZero** [comment]
Я вот не знаю насчет календарая и карты, как это релизовать) Они  у меня реализованы,что как бы будет только один такой элемент. У календаря есть еще кнопки тудей например, если нажать на нее то это у всех элементов календаря выберется сегодняшний день)

**Comment by mrNemoZero** [comment]
Хотя кажется понял, у jquery есть еще же есть контекст как входящий параметр
