### ISSUE TITLE
Префиксы классов

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-2#16]
Если HTML класс используется в js файле, то он должен начинаться с префикса js-

**Comment by mrNemoZero** [comment]
а я вот сделал, что есть класс html, а если обращаешься к нему с помощью js , я этому элементу добавляю просто класс с префиксом, для которого никаких стилей не задано,он просто существует для обращения. Сделал так т.к. проще стили делать в stylus с помощью '&', если это элемент например. А то если к элементу обращается js надо отдельно класс писать с префиксом и там стили все
