### ISSUE TITLE
Картинки у news и event

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-2#18]
Где они?:)
![image](https://user-images.githubusercontent.com/26929933/31982731-4ce80ab2-b984-11e7-92b4-2e221cab70df.png)

**Comment by mrNemoZero** [comment]
![screenshot from 2017-10-25 13-32-16](https://user-images.githubusercontent.com/16408935/31983789-0191c774-b989-11e7-9fdc-2ba46fcd0330.png)

**Comment by mrNemoZero** [comment]
а ты откуда смотрел?

**Comment by Zarwlar** [comment]
Я запускал HTML файл

**Comment by mrNemoZero** [comment]
ну вот у меня щас как бы, картинки надо вручную добавлять в папку img, т.к. когда на входе в индексе указываешь путь к картинке вэбпак не собирает их. Мжет я настроил не так. Вэбпак собирает картинки когда, они например в css фоновой запиленны
