### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-2#19]
Нет диалогов и нет фотографии)
![image](https://user-images.githubusercontent.com/26929933/31982795-946f6164-b984-11e7-8fb0-5ef4829c0a75.png)

**Comment by Zarwlar** [comment]
Сюда же)
![image](https://user-images.githubusercontent.com/26929933/31982830-c180d7c8-b984-11e7-9364-bc899430e716.png)

**Comment by mrNemoZero** [comment]
диалоги надо самому писать, это же чатик
А картинки подгружаются, когда на гихаб пейдже смотришь

**Comment by mrNemoZero** [comment]
Если через web-dev-server смотреть картинок да нет, но сделан макет,чтопуть к картинкам идет как входной параметр. А так он их подхватывает уже когда скомпилировал на вэбпаке

**Comment by mrNemoZero** [comment]
![screenshot from 2017-10-25 13-43-25](https://user-images.githubusercontent.com/16408935/31984135-859a1ef8-b98a-11e7-8b32-a69c723fafeb.png)

**Comment by mrNemoZero** [comment]
https://mrnemozero.github.io/maket-2/res/
вот тут картинки все видны

**Comment by mrNemoZero** [comment]
я просто не знаю как в реале? путь к картинкам как передется? Их же сервер дает нам, там где они лежат?

**Comment by Znack** [comment]
ну вебпак должен их раздавать, эти картинки. Я же правильно понимаю, что у тебя картинки там же в компонентах рядом лежат?

**Comment by mrNemoZero** [comment]
нет щас у меня руками в img папку кидать. Просто когда в корне(index.pug) путь пишу к картинке вэбпак их не собирает(
