### ISSUE TITLE
Различные плагины должны использоваться из node_modules

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-2#20]
Сейчас в твоих скриптах используются плагины, которые должны быть установлены глобально) Чтобы это исправить, нужно изменить пути запуска плагинов на локальные (node_modules)

Лучше сразу поправить во всех проектах :)
```
  "scripts": {
    "dev": "webpack-dev-server --config webpack/webpack.config.js",
    "build": "webpack --config webpack/webpack.config.js"
  },
```

**Comment by mrNemoZero** [comment]
Всмысле путь до вэбпака указать прямо? я думал,что везде прописывал, уже похожее ишью было)
