### ISSUE TITLE
Лишний доллар в названии

### ISSUE THREAD

**Issue by shevdi** [mrNemoZero/maket-2#22]
в stages.js. Там же просто значение

**Comment by mrNemoZero** [comment]
нет, там же jquery объект, они же доллара начинаются, сделано так, т.к. можно будет много раз создавать этот блок

**Comment by shevdi** [comment]
Я про $minValue, куда кладется значение.

**Comment by mrNemoZero** [comment]
а блин, точно они да лишние согласен))
