### ISSUE TITLE
Code style в js хромает

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-2#23]
https://github.com/mrNemoZero/maket-2/blob/master/src/blocks/stages/stages.js — вот пример файла, который говорит, что у тебя не очень линтер настроен? :) Пустые строки, нет пробелов после запятых, нарушены оступы и все почти в паре строк кода :)

**Comment by Znack** [comment]
Пример я привел только этого файла, но code style должен быть идеальный везде.

**Comment by mrNemoZero** [comment]
а я линтером только игру прогонял, здесь нет)
