### ISSUE TITLE
В стилях используй одинаковую структуру файла

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-2#24]
Файлы стилей у нас по сути почти всегда имеют одну и ту же структуру:

```
.block
  color: black
  &_mod
    color: red
  
  &__elem
    color: white
    &_elem-mod
      color: green
```

И здесь мы не повторяем название блока, а используем &__
Это позволяет явно видеть каскадность и что к чему принадлежит

**Comment by mrNemoZero** [comment]
Я вроде так и старался делать,но еще раз пройдусь)
А как со стилями у плагинов jquery? Например календарь как у меня сделан, как вы делаете?

**Comment by mrNemoZero** [comment]
А кажется понял, я че то в stages начудил

**Comment by Znack** [comment]
Оформил другое ишью по поводу календаря :)
