### ISSUE TITLE
Страницы вынести по отдельным папкам 

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-2#26]
А их в отдельную надпапку pages.
И стили тоже туда же, не надо создавать отдельный блок light_side, чтобы туда стили страницы выносить, а то получается, блок есть, а верстки для него нет :(
А потом оказывается, что верстка все-таки есть, но совершенно в другом месте

**Comment by mrNemoZero** [comment]
А как с данными быть?  У меня щас есть папка  data  с данными, но там чисто для контейнера блоков, получаетсяя мне надо сделаь из страниц миксин тоже и передевать сверху через index данные в них?

**Comment by mrNemoZero** [comment]
И еще вопрос, страниы в папках должны быть и в результате сборки тоже?

**Comment by Znack** [comment]
лучше в каждой папке со страницей определи свой файл с данными

в папках со страницами только код самих страниц, туда ничего генерить не надо вебпаком. Вебпак потом эти страницы все билдит и отправляет как разные html файлы в папку сборки

**Comment by mrNemoZero** [comment]
Я коряво написал немного, вот в папке сборки они там как должны распологаться,тоже в отдельных папках, или все вместе в корне?)

**Comment by Znack** [comment]
А, ну это уже неважно, кому какое дело, что там в папке сборки происходит :)
