### ISSUE TITLE
Архитектура скриптов

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-2#27]
Все скрипты должны быть оформлены классами в соотвествии вот с этим пунктом стандартов: https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_88gv1/

**Comment by mrNemoZero** [comment]
Вот уточнить хочу момент. возьмем пример создания процентов

> $(document).ready(() => {
  const $percentages = $('.js-percentage');
  $percentages.each(function () {
    $(this).circleProgress({
      value: $(this).data('percent') / 100,
      size: 96,
      startAngle: (Math.PI * 3) / 2,
      fill: {
        gradient: ['#e75735'],
      },
      emptyFill: 'rgba(0, 0, 0, 0)',
      thickness: 5,
    });
  });

> });

вот надо то что внутри **each** оформить как класс в который каждый DOM  будет передаваться, так?) От this еще не избавлялся

**Comment by Znack** [comment]
внутри each просто создавай инстансы класса, а сам класс можешь определить выше :)

**Comment by mrNemoZero** [comment]
пасибо0 Сразу и второй вопрос отпал)) Думал разделять этот код на два файла js и класс импортить, в одном  файле напишу))

**Comment by mrNemoZero** [comment]
Посмотри плиз блок buttons так правильно будет. У меня сразу вопрос еще)
ЛУчше же расскидать на методы весь код и уже в конструкторе их запустить?)
