### ISSUE TITLE
Обработчики событий именовать

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-2#29]
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_7qq6j/

**Comment by mrNemoZero** [comment]
А вот по поводу именований... в примере напсано:
`$(window).on('scroll.myComponent', function (event) {...})`
Меня сбивает с толку **myComponent**, мы здсь что должны указать что делает этот клик или класс компонента? Я вот хочу риппл эффект оформить таким образом, будет ли это правильно???)))
`$(this).on('click.rippleEffect', function (event) {...})`
Тогда вроде и понятно,что убираем)

**Comment by Znack** [comment]
лучше тогда 'click.buton.rippleEffect.123' <- где button — компонент, а 123 — айди компонента, который ты сам генерь для каждого инстанса
