### ISSUE TITLE
Все статичные классы в pug через точки указывать

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-2#30]
Сейчас встречается подобное: `input(type="text" class="feedback__input" placeholder="Your Name")`, но лучше бы вот так: `input.feedback__input(type="text" placeholder="Your Name")`

Как минимум, это по максимуму поддерживает однообразие стиля в коде. Бывают исключения, но это когда надо динамически генерить имена классов

**Comment by mrNemoZero** [comment]
а вот когда есть статичные и динамичский класс? Вот код:
`button(type="button" class="button js-button button_size-"+size+" button_color-"+color disabled = _disabled ? true : false) BUTTON`
вот есл переделал таким образом:
`button.button.js-button(type="button" class="button_size-"+size+" button_color-"+color disabled = _disabled ? true : false) BUTTON`
это же не правильно как то? В двух местах классы указаны можно запутаться их все же как сделать?)

**Comment by Znack** [comment]
А тут нет еще устоявшегося мнения у нас, можешь делать, как тебе кажется логичней :)

**Comment by mrNemoZero** [comment]
Ок, я тогда еще подумаю над этим)))
