### ISSUE TITLE
news & events

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-2#31]
Во-первых, сейчас оба компонента не имеют блоков)
Т.е. new__post и event__post либо являются блоками, а не элементами, либо
они должны быть обёрнуты в блоки с соответствующими названиямию
Во-вторых, слово news не изменяется в зависимости от числа)
Поэтому если мы хотим сказать о новости в единственном числе, то
должны также писать news)

**Comment by mrNemoZero** [comment]
С первым понял, при разделени блока косячнул. раньше один это блок был)
А со вторым лучше, что бы в единственном числе был? Да в множественном может запутать, это бы подошло блоку которые например список новостей показывает, а не одну новость, понял ошибку учту на будущее)

**Comment by Zarwlar** [comment]
Да, пусть просто будет news)
Если появится необходимость сделать группу новостей, то это будет, грубо говоря, блок-контейнер с классом set-of-news, news-group etc)

**Comment by mrNemoZero** [comment]
Сейчас перепрочел и понял про news) Английский надо лучше знать мне, хоть и хватает тех. доки читать)
