### ISSUE TITLE
На придуманных страницах продемонстрировать кастомизацию компонент

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-2#33]
А потом написать сюда в комментариях к ишью примеры компонент, которые на разных страницах подключаются с разными свойствами в разных темах с разными стилями.

Сейчас самодельные страницы выглядят, как демо к созданным блокам, а вместо этого хотелось бы увидеть полноценный сайт

**Comment by mrNemoZero** [comment]
Ну там две страницы привелечения на сторону силы , а третья магазин мечей.
Я не понял мне переделать и  компоненты тоже? Т.к. у меня у них два цвета отображаться могут как и в демо странице тоже.

**Comment by Zarwlar** [comment]
Нужно более разнообразное переиспользование компонент, и использовать их побольше)
Да, т.е. у тебя, как минимум, должны кастомизировать цвета. А сейчас на придуманных страницах цвет изменён только у 1 компонента. В целом, кастомизация компонента это не только цвета, здесь всё решает фантазия)

**Comment by mrNemoZero** [comment]
понял, что нибудь нафантазирую

**Comment by mrNemoZero** [comment]
Это не до конца еще сделано, можешь пиз глянуть не фигню ли я опять делаю, я просто не могу придумать, что то интересное. Тм новая страница Star Wars Galaxy of Heroes, это пародия на сайт с инфой по мобильной игре swgoh.gg. 

   Я так точно и не понял мои старые страницы можно удалить и на них не ориентироваться?

**button** используется в шапке и в aside, но они не функционирует прото так стоят.
В списке персонажей используется **search**, он также используется в  Saber Shop
**user_profile** изменил, так что бы отображались или нет соц. сети можно выбирать, в light_side она уже с соц сетями используется
На кнопку Log In можешь нажать, там будет использоваться **feedback**, **arrow**, **stages**
  **feedback** в dark_side и light_side используется
Но вот feedback типа для регстрации хотел заюзать, но его надо переделывать совсем тогда надо,
 еще е думал, что сделать(
  **arrows** юзается в футере так же, но она там возвращает назад, а здесь пока не придумал, что дальше делать. 
  **stages** в sabershope тоже есть

Пока для остальных элементов не придумал  и есть пара вопросов.
Вот map и video особо то и не заюзаешь как то иначе, чем указать место или показать видео?
Они есть в dark_side и light_side, или еще ченить придумать?)

**Comment by mrNemoZero** [comment]
Ща еще можешь на пера тыкнуть на страницу скиллов перйдет

**Comment by mrNemoZero** [comment]
traders новая страницы
Использованы компоненты 
Percantages для отображения рейтинга продавцов
User_profile  для показа лиц продавцов их должности и свзь в соцсетях
Calendar для просмотра таск-листа на каждый день

**Comment by mrNemoZero** [comment]
Добавлена страница beatytube
На ней использованн блок video для отображения простматренного видео, и для плэйлиста справа.
Tickboxes использоанан для лайков/дизлайков, еще добавлю куданить...
slider использован для отображения ретина видео, он так же используется настанице dark_side, как для размера пожертвования на постройку звезды смерти

**Comment by mrNemoZero** [comment]
теперь в traders можно тыкуниьь на продавца и получить про него инфу. Новая страница trader_info,
**Stage** используется как показатель скилла торговца,используется в swgoh для показа шагов регистрации
**Chart** для иллюстрации вклада в продажи этого сотрудника от общего, в презентации светлой стороны, с другим цветом показанно соотношение ситхов и джедаев во вселенной 
**User-profile** для данных продавца (имя, фамилия, соц.сети), используется в swgoh для показа персонажей и фракции к которой они прнадлежат

**Comment by Zarwlar** [comment]
На самом деле, сейчас у тебя продемонстрирована кастомизация на трёх компонентах, doughnut, standart button и events (или news). Остальные у тебя страницах просто переиспользуются с теми же стилями, что и на макете. Попробуй, например, сделать так, чтобы здесь вместо круглой аватарки, становилась квадратная. Поизменяй цвета у других компонент. Страницы больше можно не делать, но нужно добавить кастомизацию компонент и продемонстрировать это
![image](https://user-images.githubusercontent.com/26929933/33700983-00bf0b9e-db4f-11e7-9ff9-650fd7a45627.png)

**Comment by mrNemoZero** [comment]
сделаю, просто добавление новых цветов столько по времени уходит) Делалось то по ЮИ киту)

**Comment by mrNemoZero** [comment]
Star Wars Heroes of Galaxy
**user-profile** - изменена форма аватарки
**search**, search_select - изменены цвета
тыкни на Log In 
**arrow** - изменен цвет
**feedback** - изменен цвет
**stages** - изменен цвет
Тыкни на Sign Up
изменение те же но вних кнопка **toggle** - изменен цвет
Зайди в Help
messaging изменен цвет
На странице Beatytube
есть два **tickboxes** лайк и дизлайк они разного цвета.
**slider** в макете он зеленого цвета сделал оранжевым
Видео понятно из ютуба фрейм , так тут с разными размерами просто сделанно\
Страница Sabershop тут используется 
**Event**  c другим цветом
**map** с другим цветом

**Comment by mrNemoZero** [comment]
@Zarwlar  вот сейчас посмотришь плиз? на все элементы  кстомизированны)

**Comment by Zarwlar** [comment]
Там где есть ховер, он остался зелёным, так и было задумано?)

**Comment by mrNemoZero** [comment]
да, я не стал это переделывать. Я когда спрашивал в риззоме про например user_profile их сделать надо как ховер эффект или как два элемента с разными модификаторами.  Мне ответили как хочешь сделай) Поэтому такой эффект и есть, могу вообще убрать ховер эфекты все и пусть будут как модификаторы цвета, просто это. Я изначально начал делать так

**Comment by Zarwlar** [comment]
Окей)
