### ISSUE TITLE
На узких экранах лезет верстка

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-2#35]
![image](https://user-images.githubusercontent.com/2928964/34088273-de33dd86-e3da-11e7-9768-6b23efce81ec.png)

У тебя типичная проблема, с которой каждый верстальщик сталкивается, надо ее решить :)

Снизу осталось пустое место и надо как-то масштабировать картинку на фоне :)

**Comment by mrNemoZero** [comment]
приходить в голову идея, но тогда пропорции сломаются или это норм?)
Или например футер сделать снизу с инфой какой нибудь и он заполнит пустоту??

**Comment by Znack** [comment]
Не, пропорции ломать нельзя :)

**Comment by mrNemoZero** [comment]
Сейчас обрезается по бокам и нету снизу пустоты

**Comment by Znack** [comment]
Да на самом деле текущее решение для этого проекта норм
