### ISSUE TITLE
нельзя менять стили блоков не из файлов самого блока

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-2#37]
У тебя из страницы перетираются стили используемого блока, очень плохая практика :(
Например:
```
& > .video
```

**Comment by Znack** [comment]
Компоненты все должны быть инкапсулированы и самодостаточны. Ты не имеешь права из внешнего блока менять стили внутреннего таким вот оперированием.
Ну или имеешь право, но тогда мы твои проекты поддерживать не будем :)

**Comment by Znack** [comment]
О, так у тебя это во всех страницах практикуется, весь проект на этом, оказывается, построен :)

Кстати, требование делать кастомные страницы как раз и заставляет возиться с кастомизацией блоков и сталкиваться с этой проблемой, так что здорово, что у тебя опыт сейчас есть костылей, а теперь тебе надо грамотное и архитектурно верное решение придумать, чтобы потом без геморроя можно было проект поддерживать

**Comment by mrNemoZero** [comment]
https://github.com/mrNemoZero/maket-2/issues/12

**Comment by mrNemoZero** [comment]
Сделанно после этого ишью. Я делал так для внешних отступов. мне тогда их как и было завернуть обратно в блоки и делать для тех блоков внешние оступы?

**Comment by Znack** [comment]
Хм, там немного другое имелось ввиду, в первую очередь, что у тебя контейнеры должны быть, внутри которых уже вложенные блоки. И у контейнеров ты можешь уже менять парамтеры. То есть контейнер — по сути обертка над блоком, а эта обертка по сути элемент внешнего блока. Так как она всего лишь элемент, ты в родителе можешь ей задавать свойства. А сам блок должен просто быть самим собой в рамках родителя (родителем у него непосредственным будет контейнер вот этот)

**Comment by mrNemoZero** [comment]
у меня вроде так и было сделано изначально... просто было для каждой обертки свой класс например для button был container__button-block. А имелось ввиду походу универсальные контейнеры, т.е. создать один. Не правильно изначально понял(

**Comment by mrNemoZero** [comment]
Все равно универсвльно не сделаешь по норму. Ну сделаю я блок container__block и stylus  будет, типа:
&:nth-child(1)
&:nth-child(1)
&:nth-child(1)

**Comment by mrNemoZero** [comment]
@Znack вот так сделаль)
