### ISSUE TITLE
pixel perfect

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/maket-2#4]
Пройдись еще раз по макету. В твой верстке все должно быть также как в нем. Допускается небольшое отклонение по позиционированию и размерам элементам (и иконкам, хотя если бы они через svg были сделаны и тогда совпадали с макетом тоже было бы круто, но это уже по желанию).  

Сейчас много где не соответствие по шрифтам и в целом по верстке.

Например 

![2017-10-09 14-45-15](https://user-images.githubusercontent.com/22253666/31328704-a34d3728-ad00-11e7-94e8-d6fa49c21bc6.png)

Выглядит просто недоделанным...

И сразу по календарю. У всех такая проблема - по макету сложно понять как должно быть.

В низу "TODAY" - это кнопка по нажатию на которую должна выбираться текущая дата (сейчас в низу вообще ничего нет). 
Также сейчас  при клике на дату в календаре ничего не происходит (должна выбираться дата и кнопки календаря не должны быть ссылками).

Видео. Этот элемент в макете присутствует для того, чтобы попрактиковаться в стилизации видеоплеера, просто вставить ютюбовский не пойдет.

**Comment by mrNemoZero** [comment]
Все понял, пройдусь еще раз и уже ближе к реальности сделаю по макету.Подумал,что это просто набор элементов и не особо сильно позиционировал,ошибку понял исправлю). 
Только по чатику не понял, в макете там просто уже было введено сообщение,а тут надо ввести, или я не правильно понял что то?)
![meessage](https://user-images.githubusercontent.com/16408935/31329303-9ffbf002-ad03-11e7-81b0-135f93a2d882.png)

**Comment by mrNemoZero** [comment]
А насчет ютюба,я в риззоме спрашивал, ответили просто айфрейм ютуба вставь. Ну могу и сделать не проблема

**Comment by Burize** [comment]
Там с чатом нужно было просто сверстаться эту "формучку" а не делать функционал чата, но классно, что сделал - оставь так. 

С видео, да, оказывается теперь можно и просто фрейм вставить. Оставляй так тогда.

**Comment by mrNemoZero** [comment]
Про календарь, кнопку тудей сделал, но вот траблы с кнопками календаря. Я использую плагин jquery **datepicker** и он сам как бы сам ставит кнопки календаря ссылками. Мне что тогда самому сделать весь календарь? Или как в макете сделать просто формочку?
